{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Empty filename passed to function\n",
      "WARNING: Empty filename passed to function\n",
      "[INFO][2020/11/24 08:58:23 pm] Opening HDF file: /home/nathan/data/kraken/h2b/giulia/GV0807/Pos3/Pos3_aligned/HDF/segmented.hdf5...\n",
      "[INFO][2020/11/24 09:02:37 pm] Loading objects/obj_type_1 (408973, 5) (388394 filtered: area>=100)\n",
      "[INFO][2020/11/24 09:02:41 pm] Loading tracks/obj_type_1\n",
      "[INFO][2020/11/24 09:02:43 pm] Loading objects/obj_type_1 (408973, 5) (388394 filtered: area>=100)\n",
      "[INFO][2020/11/24 09:02:47 pm] Closing HDF file: /home/nathan/data/kraken/h2b/giulia/GV0807/Pos3/Pos3_aligned/HDF/segmented.hdf5\n",
      "ERROR:root:Unhandled exception:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/napari/_qt/qthreading.py\", line 528, in reraise\n",
      "    raise e\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/napari/_qt/qthreading.py\", line 124, in run\n",
      "    result = self.work()\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/napari/_qt/qthreading.py\", line 224, in work\n",
      "    return self._func(*self._args, **self._kwargs)\n",
      "  File \"/home/nathan/analysis/arboretum/arboretum/core.py\", line 193, in _import\n",
      "    seg, loc, tracks = utils.load_hdf(arbor.filename)\n",
      "  File \"/home/nathan/analysis/arboretum/arboretum/utils.py\", line 300, in load_hdf\n",
      "    for trk in trk_set:\n",
      "TypeError: 'Tracklet' object is not iterable\n",
      "\n",
      "[INFO][2020/11/24 09:03:21 pm] Opening HDF file: /home/nathan/data/kraken/h2b/giulia/GV0807/Pos3/Pos3_aligned/HDF/segmented.hdf5...\n",
      "INFO:worker_process:Opening HDF file: /home/nathan/data/kraken/h2b/giulia/GV0807/Pos3/Pos3_aligned/HDF/segmented.hdf5...\n",
      "[INFO][2020/11/24 09:03:33 pm] Loading objects/obj_type_1 (408973, 5) (388394 filtered: area>=100)\n",
      "INFO:worker_process:Loading objects/obj_type_1 (408973, 5) (388394 filtered: area>=100)\n",
      "[INFO][2020/11/24 09:03:37 pm] Loading tracks/obj_type_1\n",
      "INFO:worker_process:Loading tracks/obj_type_1\n",
      "[INFO][2020/11/24 09:03:39 pm] Loading objects/obj_type_1 (408973, 5) (388394 filtered: area>=100)\n",
      "INFO:worker_process:Loading objects/obj_type_1 (408973, 5) (388394 filtered: area>=100)\n",
      "[INFO][2020/11/24 09:03:43 pm] Closing HDF file: /home/nathan/data/kraken/h2b/giulia/GV0807/Pos3/Pos3_aligned/HDF/segmented.hdf5\n",
      "INFO:worker_process:Closing HDF file: /home/nathan/data/kraken/h2b/giulia/GV0807/Pos3/Pos3_aligned/HDF/segmented.hdf5\n",
      "ERROR:root:Unhandled exception:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/napari/_qt/qthreading.py\", line 528, in reraise\n",
      "    raise e\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/napari/_qt/qthreading.py\", line 124, in run\n",
      "    result = self.work()\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/napari/_qt/qthreading.py\", line 224, in work\n",
      "    return self._func(*self._args, **self._kwargs)\n",
      "  File \"/home/nathan/analysis/arboretum/arboretum/core.py\", line 193, in _import\n",
      "    seg, loc, tracks = utils.load_hdf(arbor.filename)\n",
      "  File \"/home/nathan/analysis/arboretum/arboretum/utils.py\", line 300, in load_hdf\n",
      "    for trk in trk_set:\n",
      "TypeError: 'Tracklet' object is not iterable\n",
      "\n",
      "[INFO][2020/11/24 09:04:32 pm] Opening HDF file: /home/nathan/data/kraken/h2b/giulia/GV0812/Pos3/Pos3_aligned/HDF/segmented.hdf5...\n",
      "INFO:worker_process:Opening HDF file: /home/nathan/data/kraken/h2b/giulia/GV0812/Pos3/Pos3_aligned/HDF/segmented.hdf5...\n",
      "[INFO][2020/11/24 09:04:32 pm] Loading segmentation\n",
      "INFO:worker_process:Loading segmentation\n",
      "[INFO][2020/11/24 09:04:37 pm] Loading tracks/obj_type_1\n",
      "INFO:worker_process:Loading tracks/obj_type_1\n",
      "[INFO][2020/11/24 09:04:39 pm] Loading objects/obj_type_1 (205743, 5) (192777 filtered: area>=100)\n",
      "INFO:worker_process:Loading objects/obj_type_1 (205743, 5) (192777 filtered: area>=100)\n",
      "[INFO][2020/11/24 09:04:41 pm] Loading tracks/obj_type_2\n",
      "INFO:worker_process:Loading tracks/obj_type_2\n",
      "[INFO][2020/11/24 09:04:41 pm] Loading objects/obj_type_2 (39202, 5) (33022 filtered: area>=100)\n",
      "INFO:worker_process:Loading objects/obj_type_2 (39202, 5) (33022 filtered: area>=100)\n",
      "[INFO][2020/11/24 09:04:41 pm] Closing HDF file: /home/nathan/data/kraken/h2b/giulia/GV0812/Pos3/Pos3_aligned/HDF/segmented.hdf5\n",
      "INFO:worker_process:Closing HDF file: /home/nathan/data/kraken/h2b/giulia/GV0812/Pos3/Pos3_aligned/HDF/segmented.hdf5\n",
      "ERROR:root:Unhandled exception:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/vispy/app/backends/_qt.py\", line 476, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/vispy/app/base.py\", line 213, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/napari/_qt/qt_viewer.py\", line 625, in on_mouse_move\n",
      "    self.viewer.cursor.position = self._map_canvas2world(list(event.pos))\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/napari/components/cursor.py\", line 55, in position\n",
      "    self.events.position()\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/napari/utils/events/event.py\", line 514, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/napari/utils/events/event.py\", line 535, in _invoke_callback\n",
      "    cb_event=(cb, event),\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/napari/utils/events/event.py\", line 529, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/napari/components/viewer_model.py\", line 394, in _on_cursor_position_change\n",
      "    layer.position = self.cursor.position\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/napari/layers/base/base.py\", line 486, in position\n",
      "    self._update_value_and_status()\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/napari/layers/base/base.py\", line 904, in _update_value_and_status\n",
      "    self._value = self.get_value()\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/napari/layers/base/base.py\", line 866, in get_value\n",
      "    return self._get_value()\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/napari/layers/image/image.py\", line 781, in _get_value\n",
      "    coord = self.coordinates\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/napari/layers/base/base.py\", line 900, in coordinates\n",
      "    return tuple(self._transforms[1:].simplified.inverse(self.position))\n",
      "  File \"/home/nathan/anaconda3/lib/python3.7/site-packages/napari/utils/transforms/transforms.py\", line 330, in __call__\n",
      "    ] = self.linear_matrix\n",
      "ValueError: could not broadcast input array from shape (3,3) into shape (2,2)\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import arboretum\n",
    "\n",
    "from skimage import io\n",
    "\n",
    "arboretum.run()\n",
    "\n",
    "seg = io.imread('/home/nathan/data/kraken/h2b/giulia/GV0807/Pos3/Pos3_aligned/HDF/segmented.hdf5')\n",
    "\n",
    "#arboretum.run(segmentation = seg)\n",
    "\n",
    "arboretum.run()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
